repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-xml
      - id: debug-statements
      - id: check-added-large-files
      - id: check-case-conflict
      - id: detect-private-key
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: \.py$
        args: [--line-length=120]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        files: \.py$

  - repo: https://github.com/resmio/pre-commit-doctoc
    rev: v1.0.0
    hooks:
      - id: doctoc
        args: [--title=## Table of Contents]

default_language_version:
  python: python3

fail_fast: true

exclude: |
  (?x)^(
      migrations/  # Exclude migrations
      | tests/     # Exclude tests
  )
